services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestion_docente_uc_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - gestion_docente_uc

  web:
    image: nginx:stable-alpine
    container_name: gestion_docente_uc_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - gestion_docente_uc
  mysql:
    image: mysql:8.0
    container_name: gestion_docente_uc_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: gestion_docente
      MYSQL_USER: ucuser
      MYSQL_PASSWORD: ucpass
    ports:
      - "3308:3306"     # XAMPP queda en 3307; Docker usa 3308

    command: --default-authentication-plugin=mysql_native_password

    volumes:
      - db_data:/var/lib/mysql
      
    networks:
      - gestion_docente_uc
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: gestion_docente_uc_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - gestion_docente_uc
volumes: 
  db_data:
#definicion de la red interna
networks:
  gestion_docente_uc:
    driver: bridge #tipo de red:bridge (predeterminada), host, none
